name: speech_to_text_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  # recording words
  speech_to_text: ^5.4.3

  # floating action button effect
  avatar_glow: ^2.0.2

  # launch apps, browser & email
  url_launcher: ^6.1.0

  # copy text to clipboard
  clipboard: ^0.1.3

  # provider
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true